# Generated by Django 6.0.2 on 2026-03-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_conversation_chatmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='candidate_last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='hr_last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
