# Generated by Django 6.0.1 on 2026-03-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_jobmatchresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmatchresult',
            name='engine_version',
            field=models.CharField(default='legacy', max_length=32),
        ),
    ]
