# Generated by Django 6.0.2 on 2026-03-09 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_chatmessage_attachment_alter_chatmessage_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='chatmsg_conv_created_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'sender', 'created_at'], name='chatmsg_conv_sender_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['hr', 'updated_at'], name='conv_hr_upd_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['candidate', 'updated_at'], name='conv_cand_upd_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['job', 'created_at'], name='jobapp_job_created_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['applicant', 'created_at'], name='jobapp_app_created_idx'),
        ),
        migrations.AddIndex(
            model_name='jobmatchresult',
            index=models.Index(fields=['candidate', 'engine_version'], name='jobmatch_cand_eng_idx'),
        ),
    ]
