# Generated by Django 6.0.2 on 2026-03-02 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobcore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='phone_number',
        ),
    ]
