# Generated by Django 6.0.2 on 2026-03-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcore', '0002_remove_candidateprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='profiles/cvs/'),
        ),
    ]
